### ISSUE TITLE
void-function sideline-eglot

### ISSUE THREAD

**Issue by andrewbanchich** [emacs-sideline/sideline-eglot#2]
after adding the example in the README to my config, i get:

```
Sideline mode enabled in current buffer
Error running timer ‘sideline-render’: (void-function sideline-eglot)
```

**Comment by jcs090218** [comment]
Did you install the package? 🤔 the function is autoload, so it should be there.

**Comment by andrewbanchich** [comment]
I just added the snippet in the README, which doesn't look like it installs it. Wasn't sure if `sideline` would do that for me. MELPA doesn't seem to have it available yet.

**Comment by jcs090218** [comment]
The snippet in the README wouldn't install the package for you. You would have to install it yourself.

> Wasn't sure if sideline would do that for me.

It depends on the package installer you are using. Suppose you are using the `package.el` (default), the answer is yes!

> MELPA doesn't seem to have it available yet.

See https://github.com/emacs-sideline/sideline-eglot/issues/1#issuecomment-1871507068.

**Comment by jcs090218** [comment]
I've changed the documentation. It should be much more straightforward.
