### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by joaotavora** [emacs-sideline/sideline-eglot#3]
https://github.com/emacs-sideline/sideline-eglot/blob/2a7f641dd75fa4a181b056554ac95add6510745a/sideline-eglot.el#L63

For true async actions, you should probably use `jsonrpc-async-request` directly.  You can get the server, if it exists with `eglot-current-server`.

https://github.com/emacs-sideline/sideline-eglot/blob/2a7f641dd75fa4a181b056554ac95add6510745a/sideline-eglot.el#L74

Likewise here, you should use `eglot-current-server`, not `--` symbols

**Comment by jcs090218** [comment]
Thanks for the advice! I'll improve it when I have time!

Cheers!

**Comment by jcs090218** [comment]
Resolved in #5. Thanks to @DevelopmentCool2449!
